### ISSUE TITLE
Inclusão de conferências

### ISSUE THREAD

**Issue by igorsteinmacher** [ppgcc/calculaQualis#1]
Parabéns pela iniciativa!!! Gostaria de saber como podemos adicionar conferências para que o script disponibilize a métrica na página

**Comment by olimarborges** [comment]
Olá Igor, obrigado! Desculpe pela demora no retorno, só vi a issue hoje. 
Sobre a adição de conferências, estamos utilizando apenas as listadas na [Planilha de Trabalho da CC](https://docs.google.com/spreadsheets/d/1vYzEllNS-OjmRQFvdnTUR4-y2Pq0BE9QjK5FH5eVA3M/edit?usp=sharing). Pois elas foram analisadas pelas Comissões Especiais da SBC. 
Obrigado!
